/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { generalizedErrorMessageForLocale, redactSecrets } from '@maka/core/redaction';
import type { SubscriptionActionCode, SubscriptionActionFailureReason } from '@maka/core/oauth-subscription';
import { type UiCatalog, type UiLocale, lookupCopy } from '@maka/core/ui-locale';

type SubscriptionResultCode =
  | SubscriptionActionCode
  | Extract<
      SubscriptionActionFailureReason,
      'experimental_disabled' | 'login_in_progress' | 'presentation_failed'
    >;

type WidenCopy<T> = T extends string
  ? string
  : T extends (...args: infer Args) => string
    ? (...args: Args) => string
    : { [K in keyof T]: WidenCopy<T[K]> };

// Capability-section strings for the connection detail page — the add-provider
// form deliberately carries no declaration controls (capabilities are edited
// after the connection exists).
const zhCapabilitiesCopy = {
  capabilities: '能力',
  modelDisplayName: '显示名称',
  modelDisplayNameHelp: '仅用于显示；请求仍使用模型 ID。',
  thinkingEffort: '思考强度',
  thinkingEffortHelp: '勾选服务商支持的强度，供对话时选择。留空时按模型资料设置。',
  thinkingUndeclared: '自动',
  thinkingSelectedCount: (count: number) => `已选 ${count} 项`,
  defaultThinkingLevel: '默认思考级别',
  defaultThinkingLevelHelp: '新任务使用此模型时采用的思考级别；任务内仍可单独切换。',
  providerDefaultThinking: '服务商默认',
  visionInput: '图片识别',
  visionInputHelp: '此服务商的模型是否支持图片。自动按模型资料判断，缺少资料时不发送图片。',
  visionDefaultOption: (supported: boolean | undefined) =>
    supported === undefined ? '自动' : supported ? '自动 · 支持' : '自动 · 不支持',
  visionEnabledOption: '支持',
  visionDisabledOption: '不支持',
  contextWindow: '上下文窗口',
  inputLimit: '输入上限',
  inputLimitHelp: '单次请求可输入的 token 数。留空时按模型资料设置。',
  modelLimitsConflict: '输入上限不能超过上下文窗口。',
  contextWindowHelp: '模型可处理的 token 总量。留空时按模型资料设置。',
  compactionThreshold: '压缩阈值',
  compactionThresholdHelp: '达到此 token 数时压缩上下文。留空则不主动压缩。',
  maxOutputTokens: '输出上限',
  maxOutputTokensHelp: '单次回复的输出 token 上限，含思考。留空自动设置。',
  fastMode: 'Fast 模式',
  fastModeHelp: '选择更快的服务档位，可能产生额外费用。',
  fastAuto: '自动',
  fastEnabled: 'Fast',
};

const zhTwCapabilitiesCopy = {
  capabilities: '能力',
  modelDisplayName: '顯示名稱',
  modelDisplayNameHelp: '僅供顯示；請求仍使用模型 ID。',
  thinkingEffort: '思考強度',
  thinkingEffortHelp: '勾選服務商支援的強度，供對話時選擇。留空時依模型資料設定。',
  thinkingUndeclared: '自動',
  thinkingSelectedCount: (count: number) => `已選 ${count} 項`,
  defaultThinkingLevel: '預設思考級別',
  defaultThinkingLevelHelp: '新任務使用此模型時採用的思考級別；任務內仍可單獨切換。',
  providerDefaultThinking: '服務商預設',
  visionInput: '圖片辨識',
  visionInputHelp: '此服務商的模型是否支援圖片。自動依模型資料判斷，缺少資料時不傳送圖片。',
  visionDefaultOption: (supported: boolean | undefined) =>
    supported === undefined ? '自動' : supported ? '自動 · 支援' : '自動 · 不支援',
  visionEnabledOption: '支援',
  visionDisabledOption: '不支援',
  contextWindow: '上下文視窗',
  inputLimit: '輸入上限',
  inputLimitHelp: '單次請求可輸入的 token 數。留空時依模型資料設定。',
  modelLimitsConflict: '輸入上限不能超過上下文視窗。',
  contextWindowHelp: '模型可處理的 token 總量。留空時依模型資料設定。',
  compactionThreshold: '壓縮門檻',
  compactionThresholdHelp: '達到此 token 數時壓縮上下文。留空則不主動壓縮。',
  maxOutputTokens: '輸出上限',
  maxOutputTokensHelp: '單次回覆的輸出 token 上限，含思考。留空自動設定。',
  fastMode: 'Fast 模式',
  fastModeHelp: '選擇更快的服務檔位，可能產生額外費用。',
  fastAuto: '自動',
  fastEnabled: 'Fast',
};
const enCapabilitiesCopy = {
  capabilities: 'Capabilities',
  modelDisplayName: 'Display name',
  modelDisplayNameHelp: 'A label for this model. Requests still use the exact model ID.',
  thinkingEffort: 'Available thinking levels',
  thinkingEffortHelp: 'These levels appear in the conversation’s thinking selector. Select only levels supported by this provider. Leave all unchecked to use existing model information.',
  thinkingUndeclared: 'Use model options',
  thinkingSelectedCount: (count: number) => `${count} levels available`,
  defaultThinkingLevel: 'Default thinking level',
  defaultThinkingLevelHelp: 'Thinking level for new tasks that use this model. It can still be changed per task.',
  providerDefaultThinking: 'Provider default',
  visionInput: 'Send images to the model',
  visionInputHelp: 'Use provider and model information to decide whether to send images. Images are not sent when information is missing. Before choosing “Allow images”, confirm this provider supports images for this model.',
  visionDefaultOption: (supported: boolean | undefined) =>
    supported === undefined ? 'Use model information' : supported ? 'Model information: allow images' : 'Model information: no images',
  visionEnabledOption: 'Allow images',
  visionDisabledOption: 'Do not send images',
  contextWindow: 'Context window',
  inputLimit: 'Input limit',
  inputLimitHelp: 'Maximum input tokens per request. Leave empty to use model information.',
  modelLimitsConflict: 'The input limit cannot exceed the context window.',
  contextWindowHelp: 'Model capacity offered by this provider. Leave empty to use known information.',
  compactionThreshold: 'Compaction threshold',
  compactionThresholdHelp: 'Compact at this token count. Leave empty to disable proactive compaction.',
  maxOutputTokens: 'Maximum output',
  maxOutputTokensHelp: 'Output token budget per reply, including thinking. Leave empty for automatic limits.',
  fastMode: 'Fast mode',
  fastModeHelp: 'Use the faster service tier. Additional charges may apply.',
  fastAuto: 'Auto',
  fastEnabled: 'Fast',
};

const zhCopy = {
  detail: {
    delete: '删除', cancel: '取消', deleteUnused: '不再需要，删除连接',
    deleteFailed: '删除模型连接失败', credentialReadFailed: '读取模型凭据状态失败', refreshFailed: '刷新模型连接失败',
    saveFailed: '保存模型连接失败', saveModelsFailed: '保存启用模型失败',
    modelKey: '模型密钥', pasteModelKey: '粘贴模型密钥', getModelKey: '获取模型密钥', saving: '保存中…',
    advancedRequest: '高级请求设置', advancedRequestHelp: '为这个连接的 HTTP 请求添加请求头和额外 JSON 请求体。请求头值作为凭据保存在本机。',
    requestHeaders: '自定义请求头', headerName: '请求头名称', headerValue: '请求头值', retainedHeaderValue: '保留已保存的值', addHeader: '添加请求头', removeHeader: '移除', noRequestHeaders: '未设置自定义请求头。',
    extraRequestBody: '额外请求体（JSON）', extraRequestBodyHelp: '仅添加顶层字段；若与 Maka 生成的字段重名，请求会明确失败。', requestCustomizationInvalid: '请求设置无效', requestHeadersInvalidDetail: '请检查请求头名称和值。', requestBodyInvalidDetail: '请输入符合要求的 JSON 对象。', saveAdvancedRequest: '保存高级请求设置', configuredHeaders: (count: number) => `${count} 个请求头`, noAdvancedRequest: '未设置',
    oauthLoggedIn: 'OAuth 已登录', oauthLoading: 'OAuth 状态读取中', oauthUnknown: 'OAuth 状态未知', oauthWaiting: '等待 OAuth 登录',
    oauthLoggedInDetail: '该模型连接使用主进程保存的 OAuth access token；若请求提示需要重新登录，请到账号连接重新授权。',
    oauthLoadingDetail: '正在读取本机 OAuth 登录状态，读取完成前不会把未知状态显示成未登录。',
    oauthUnknownDetail: '暂时无法读取本机 OAuth 登录状态；请刷新页面或重新打开设置。',
    oauthWaitingDetail: '请到账号连接完成登录；登录成功后会自动出现在模型连接里。',
    providerRetired: '此模型服务已停用',
    providerRetiredDetail:
      '这条连接已无法用于对话。请添加其他模型连接，并选择新的默认模型；原有对话记录会保留。',
    credentialLoadingDetail: '正在读取模型凭据状态，读取完成前暂不测试连接或刷新模型。',
    credentialUnknownDetail: '模型凭据状态暂时没刷新成功，已避免把未知状态显示成未登录或未配置。',
    testConnection: '测试连接',
    updateModels: '更新模型目录', endpoint: '服务地址',
    connectionName: '名称',
    connectionNamePlaceholder: '给这个连接起个名字',
    addModel: '添加模型',
    addModelConfirm: '添加',
    addModelIdField: '模型 ID',
    addModelIdFieldHelp: '需与服务商完全一致，区分大小写。',
    addModelIdPlaceholder: 'deepseek-v4-flash-0731',
    addModelIdRequired: '请填写模型 ID。',
    addModelIdDuplicate: '该模型已在列表中。',
    addModelContextWindow: '上下文窗口',
    addModelContextWindowHelp: '服务商模型页给出的最大 token 数。缺少它 Maka 只能按 32k 处理，长对话会被提前截断。',
    addModelContextWindowRequired: '请填写上下文窗口。',
    contextWindowInputInvalid: '请输入正整数 token 数或 K/M 缩写，例如 128000、128K、1.5M。',
    credentials: '连接', dangerZone: '删除连接', deleteRowHelp: '此操作不可撤销。',
    credentialsHelp: '密钥只保存在本机。',
    credentialsHelpAccount: '登录令牌只保存在本机。',
    modelManagementHelp: '这些模型会出现在任务的模型选择器里。',
    ...zhCapabilitiesCopy,
    capabilitiesHelp: '仅应用于此连接中的这个模型，保存后生效。',
    // Row affordances (settings-sidebar 的 InfoRow / ExpandableRow 语言)：一行
    // 只报状态，改的时候才展开成输入框。
    change: '更换', set: '设置', edit: '编辑', save: '保存',
    endpointManaged: '由账号登录或服务商管理',
    endpointMissing: '尚未配置服务地址',
    endpointModelOverridesNote: '部分模型会通过其他服务端点发送请求',
    endpointCredentialsMasked: '已保存的地址内嵌凭据,编辑时默认隐藏',
    modelManagement: '模型',
    disconnectAndDelete: '退出账号并删除',
    login: '登录', loggingIn: '登录中…', relogin: '重新登录',
    oauthReloginDetail: '若请求提示需要重新登录，点这里重新走一遍授权。', deviceCode: '登录码：',
    oauthStartDetail: '点下方按钮打开浏览器完成登录，授权成功后会自动刷新这里的状态。',
    status: '连接状态', statusHealthy: '正常', statusUntested: '未测试',
    modelsSummary: (enabled: number, total: number) => `已启用 ${enabled} / ${total}`,
    filterModels: '搜索模型', noModelsMatch: '未找到匹配的模型',
    enableModelAria: (name: string) => `启用模型 ${name}`,
    declareCapabilities: '配置参数', declareCapabilitiesAria: (name: string) => `配置模型参数：${name}`,
    modelUndescribed: '待配置参数',
    noModels: '暂无可选模型，请先更新模型目录。',
    keySet: '已设置', statusLoading: '正在读取状态', credentialUnknown: '凭据状态未知', keyMissing: '尚未设置密钥',
    keyTroubleshooting: '模型密钥 / 服务地址 / 代理设置', endpointTroubleshooting: '本地服务 / 服务地址 / 代理设置', oauthTroubleshooting: 'OAuth 登录 / 代理设置',
    unknownDescription: (provider: string) => `该连接使用的 provider「${provider}」在当前版本未注册。配置和凭据会保留，切回支持它的版本即可继续使用。`,
    deleteProviderTitle: (name: string) => `删除供应商 ${name}？`,
    deleteConnectionTitle: (name: string) => `删除模型连接 ${name}？`,
    deleteUnknownDescription: '删除后，支持该 provider 的其他版本也无法恢复这条连接及其凭据。',
    deleteDescription: (isDefault: boolean, disconnectsAccount: boolean) => [
      disconnectsAccount
        ? '这会退出本机账号、删除 OAuth 凭据和模型连接；刷新后不会自动重新创建。'
        : '这会删除模型连接及其本机凭据；如需再次使用，需要重新添加。',
      isDefault
        ? '它当前是默认连接；删除后默认模型会变成未设置，已有任务可能需要重新选择模型。'
        : '',
    ].filter(Boolean).join(' '),
    connectionSuccess: (name: string) => `连接成功 · ${name}`, connectionFailed: (name: string) => `连接失败 · ${name}`,
    connectionFallbackTitle: (name: string) => `连接可用 · ${name}`,
    connectionFallbackDetail: (selected: readonly string[], tested: string) =>
      `你选择的 ${selected.join('、')} 当前未响应，已改用 ${tested} 验证连接可用；任务中继续使用你选择的模型可能会失败。`,
    connectionTestError: (name: string) => `连接测试出错 · ${name}`, modelsFetched: (count: number, name: string) => `已拉取 ${count} 个模型 · ${name}`,
    modelsFetchFailed: (name: string) => `拉取模型失败 · ${name}`,
    modelsFetchFailedDetail: (message: string, troubleshooting: string) => `${message} · 当前继续显示静态列表，请确认 ${troubleshooting} 后重试。`,
    authTroubleshooting: (value: string) => `鉴权失败，请确认 ${value} 后重试。`, recheckTroubleshooting: (value: string) => `检查 ${value} 后重试。`,
    modelKeyAria: (name: string) => `${name} 模型密钥`,
    usage: {
      title: '账户用量',
      refresh: '刷新',
      refreshing: '刷新中…',
      current: '当前使用',
      unavailable: '暂时取不到用量数据。',
      unsupported: '该连接不支持查看用量。',
      unauthorized: '用量读取被拒绝：密钥可能已失效或权限不足，请更新模型密钥后重试。',
      partiallyUnauthorized: '部分用量数据被拒绝：密钥缺少相应权限，以下为可读取的部分。请更新模型密钥后重试。',
      windowLabels: { fiveHour: '5 小时窗口', weekly: '每周窗口', monthly: '月额度' },
      requests: '请求',
      failed: (count: number) => `失败 ${count}`,
      successRate: '成功率',
      cost: '花费',
      tokens: 'Token',
      tokensBreakdown: (input: string, output: string) => `${input} 入 / ${output} 出`,
      resetsAt: (when: string) => `重置于 ${when}`,
      periodEnd: (when: string) => `账期截止 ${when}`,
      updatedAt: (when: string) => `更新于 ${when}`,
      unlimited: '不限',
    },
  },
  shared: {
    connectionStale: '连接状态已更新，请刷新列表后再删除。',
    actionFallback: '模型连接服务暂时不可用，请稍后重试。', rateLimit: '当前账号或模型服务触发速率限制，请稍后重试。',
    timeout: '请求超时，请检查网络或代理后重试。', unavailable: '模型服务暂时不可用，请稍后重试。',
    network: '网络错误，请检查服务地址或代理设置后重试。', statusUnavailable: '连接测试状态暂时无法显示，请重新测试。',
    // Every list that a search box narrows says how many rows are left, so the
    // change is spoken rather than only shown.
    filterMatches: (count: number) => (count === 0 ? '没有匹配的结果' : `${count} 个匹配结果`),
    connectionStatuses: { retired: '已停用 · 请删除', reauth: '需要重新登录', disabledFailed: '暂不可用 · 上次连接失败', disabled: '暂不可用', failed: '上次连接失败' },
    lastTest: {
      auth: '鉴权失败', timeout: '请求超时', provider_unavailable: '模型服务返回错误', network: '网络错误', invalid_response: '模型服务返回错误', unknown: '连接测试失败',
    },
  },
  panel: {
    groups: { recommended: '推荐', plans: '订阅计划', api: 'API', aggregators: '聚合服务', local: '本地' },
    loadFailed: '载入模型连接失败', loadingAria: '正在加载模型供应商', connections: '模型连接',
    connectionsHelp: '已启用的模型会显示在任务的模型选择器中。',
    retry: '点击重试。', empty: '还没有模型连接', connectionRemoved: '原连接已被删除或移除，已返回模型连接列表。',
    connectedLoading: '连接已添加，正在载入详情…', connectedLoadFailed: '连接已添加，但暂时无法刷新连接列表。',
    connectionIdentityChanged: '新连接的身份与登录结果不一致，请返回连接列表后重试。',
    emptyHelp: '从下方的常用服务商开始，或浏览全部服务商。', recommended: '推荐服务商', browseAll: '查看全部服务商',
    default: '默认', setDefault: '设为默认', setDefaultTitle: '让新任务默认使用这个连接', setDefaultPending: '设置中…', setDefaultFailed: '设为默认失败', addHelp: '选择账号登录、模型计划、API、聚合服务或本地运行时。',
    searchPlaceholder: '搜索服务商', searchAria: '搜索模型服务商', noMatch: '未找到匹配的服务商', clearSearch: '清除搜索',
    createSubtitle: '完成必要配置后，连接会出现在模型页上方。', connection: '模型连接',
    count: (value: number) => `· ${value}`, modelCount: (value: number) => `${value} 个模型`, connectTitle: (name: string) => `连接 ${name}`,
    chipAria: (name: string, provider: string, isDefault: boolean, status?: string) => `模型连接：${name}，供应商：${provider}${isDefault ? '，默认连接' : ''}${status ? `，${status}` : ''}`,
    addConnection: '添加连接', backToList: '返回模型连接', backToCatalog: '返回服务商列表',
  },
  catalog: {
    unavailable: '未开放',
    cardAria: (name: string, description: string) => `添加模型供应商：${name}，${description}`,
  },
  add: {
    slugIssues: { required: '请填写连接标识', format: '连接标识只能包含小写字母、数字和连字符', too_long: '连接标识不能超过 64 个字符' }, duplicateSlug: '连接标识已存在', cloudflareAccount: '请填写 Cloudflare Account ID', endpointRequired: '这个供应商需要填写服务地址',
    accountLogin: '请到账号连接完成登录；登录成功后会自动创建模型连接。',
    apiKeyPlaceholder: '输入或粘贴 API Key', cancel: '取消', accountTitle: '使用账号连接登录',
    advancedRequest: '高级请求设置', expandAdvancedRequest: '展开高级请求设置', collapseAdvancedRequest: '收起高级请求设置',
    requestHeaders: '自定义请求头', headerName: '请求头名称', headerValue: '请求头值', retainedHeaderValue: '保留已保存的值', addHeader: '添加请求头', removeHeader: '移除', noRequestHeaders: '未设置自定义请求头。',
    extraRequestBody: '额外请求体（JSON）', extraRequestBodyHelp: '仅添加顶层字段；与 Maka 生成字段重名时会明确失败。请求头值将作为凭据保存在本机。', requestCustomizationInvalid: '请检查高级请求设置。',
    accountDetail: '不要在这里手动添加；请回到模型连接页的账号连接完成登录，Maka 会自动创建并刷新模型连接。',
    slug: '连接标识', name: '显示名称',
    accountIdPlaceholder: '填写账户 ID',
    saving: '保存中…', save: '保存供应商', keyRequired: (name: string) => `请填写 ${name} API Key`,
    apiKeyLabel: 'API Key', accountIdLabel: 'Cloudflare Account ID', endpointLabel: '服务地址',
    defaultModel: '默认模型', defaultModelPlaceholder: '留空即可，保存后自动拉取', defaultModelHelp: '保存后 Maka 会向该端点拉取模型目录。只有当端点不提供目录时，才需要在这里手填一个模型 ID。',
    stepsAria: '添加连接步骤', stepCredentials: '密钥', stepModels: '选择模型',
    onboardingVerifyAndChoose: '验证并选择模型', onboardingVerifying: '正在验证密钥并获取模型…',
    onboardingChooseModels: '选择此连接使用的模型', onboardingChooseModelsHelp: '添加后仍可在连接详情中启用其他模型。', onboardingEnabledModels: '启用的模型', onboardingSearchModels: '搜索模型', onboardingAddConnection: '添加连接', onboardingBack: '返回修改',
    onboardingSelectedCount: (selected: number, total: number) => `已选 ${selected} / ${total}`, onboardingSelectAll: '全选', onboardingClearAll: '取消全选', onboardingNoModelsMatch: '未找到匹配的模型',
    onboardingDefaultModel: '默认模型', onboardingDefaultModelHelp: '新任务将默认使用此模型，仅可在已勾选的模型中选择。',
    onboardingAuthFailed: '密钥验证失败，请检查后重试。', onboardingTimeout: '验证超时，请检查网络或代理后重试。', onboardingNetwork: '无法连接模型服务，请检查网络、代理或服务地址。', onboardingUnavailable: '模型连接服务暂时不可用，请稍后重试。', onboardingInvalidResponse: '模型服务返回了无法识别的结果，请稍后重试。', onboardingCatalogFull: '连接数量已达上限，请先删除不再使用的连接。', onboardingModelsChanged: '可用模型已发生变化，请重新验证后选择。', onboardingNoModels: '没有发现可用模型，当前未创建连接。', onboardingSelectModel: '请至少启用一个模型。',
    onboardingOutcomeUnknown: '保存结果暂时无法确认', onboardingOutcomeUnknownDetail: '请勿再次添加，以免创建重复连接。重新加载连接列表并检查该连接是否已经出现；仍不确定时请先重连 Runtime Host。', onboardingReloadConnections: '重新加载连接列表', onboardingRestart: '仍要添加另一个连接',
    ...zhCapabilitiesCopy,
  },
  oauthFlow: {
    refreshFailed: '刷新登录状态失败', accountActionFailed: (name: string) => `${name} 账号操作失败`, loginFailedRetry: '登录失败，请稍后重试。',
    retry: '请稍后再试。', startFailed: '无法开始登录', startFailedRetry: '无法开始登录，请稍后再试。', openFailed: '无法打开浏览器',
    openFailedRetry: '无法打开浏览器，请稍后重试。', loginSuccess: '登录成功', bound: (name: string) => `${name} 已绑定本机。`,
    incomplete: '登录未完成', incompleteRetry: '登录未完成，请重新打开浏览器授权。', loginFailed: '登录失败',
    logoutDescription: '将删除本机保存的订阅凭据，之后需要重新登录才能继续使用这些 OAuth 模型。', logout: '退出登录', cancel: '取消',
    loggedOut: '已退出登录', credentialsCleared: '本地凭据已清除。', logoutFailed: '退出失败', logoutFailedRetry: '退出登录失败，请稍后重试。',
    serviceUnavailable: '登录服务暂时不可用，请检查网络后重试。',
    logoutTitle: (name: string) => `退出 ${name} 登录？`,
    resultCodes: {
      copilot_classic_pat_unsupported: 'GitHub Copilot 不支持 classic PAT；请使用兼容 OAuth 登录或具有 Copilot Requests 权限的 fine-grained PAT。',
      copilot_credential_type_unsupported: '当前 GitHub 凭据类型不受支持；请使用兼容 OAuth 登录或 fine-grained PAT。',
      copilot_local_credential_missing: '未找到可导入的 GitHub 凭据；请先使用 gh 登录或配置兼容凭据。',
      copilot_import_no_credential: 'GitHub Copilot 登录没有产生可用凭据。',
      copilot_import_superseded: 'GitHub Copilot 账号在导入期间发生变化，请重试。',
      copilot_subscription_unavailable: '当前 GitHub 账号没有可用的 Copilot 订阅权限。',
      copilot_credential_import_rejected: '当前 GitHub 凭据无法导入，请检查凭据后重试。',
      copilot_subscription_check_failed: '暂时无法验证 GitHub Copilot 订阅状态，请稍后重试。',
      copilot_import_commit_failed: 'GitHub Copilot 登录未能写入 Runtime Host。',
      experimental_disabled: '本机未启用该账号登录方式；可改用导入兼容凭据，或由管理员启用后重试。',
      login_in_progress: '上一轮登录仍在进行，等它结束后再点登录。',
      presentation_failed: '无法打开系统浏览器完成登录，请检查是否拦截了弹窗后重试。',
    } satisfies Record<SubscriptionResultCode, string>,
  },
  oauthSection: {
    signedIn: '已登录', codexDescription: '使用 ChatGPT Plus / Pro 账号添加连接。', xaiDescription: '使用 SuperGrok / X Premium 账号添加连接。',
    configuredConnections: (count: number) => `已有 ${count} 个连接 · 添加另一个账号`,
    copilotDescription: '使用 GitHub 登录连接 Copilot 订阅，或导入兼容凭据。', serviceUnavailable: '登录服务暂时不可用，请检查网络后重试。',
    aria: 'OAuth 登录',
    staleState: 'OAuth 登录状态暂时没刷新成功，已保留上一次状态。',
    codexDetail: '点击下方按钮打开设备授权页，并在页面中输入这里显示的登录码。', xaiDetail: '点击下方按钮打开浏览器登录，授权完成后会自动回写。', deviceCode: '登录码：',
    openingBrowser: '打开浏览器…', waitingAuthorization: '等待浏览器授权…', logout: '退出登录', loggingOut: '退出中…',
    copilotSubtitle: '使用 GitHub 登录，或导入兼容凭据；token 不会暴露给渲染进程。', copilotImported: '已导入 GitHub Copilot 订阅账号。',
    copilotSetup: '使用 GitHub 登录以连接 Copilot，或导入已有的 gh 凭据。', importing: '导入中…',
    copilotSignIn: '使用 GitHub 登录', copilotActionFailed: 'GitHub Copilot 账号操作失败',
    copilotSignInDisabledHint: '本机未启用 GitHub 登录；请改用导入兼容凭据，或由管理员启用后重试。',
    importCredential: '导入兼容凭据',
    loadingAccount: '正在加载账号状态…', authorizing: '请在弹出的浏览器窗口完成登录。', refreshing: '正在刷新访问令牌…', refreshTokenFailed: '令牌刷新失败，请重新登录。',
    cardAria: (intent: 'add' | 'import' | 'manage', name: string, status: string | undefined, description: string) => `${intent === 'add' ? '添加' : intent === 'import' ? '导入' : '管理'}账号连接：${name}${status ? `，状态：${status}` : ''}，${description.replace(/[。.!！？?]+$/u, '')}`,
    connectTitle: (name: string) => `连接 ${name}`, addAccountTitle: (name: string) => `添加 ${name} 账号`, login: (name: string) => `登录 ${name}`, loginAndAdd: '登录并添加', signedOut: (name: string) => `${name} 尚未登录。`,
    storageFailed: (name: string) => `${name} 本地凭据读取失败，请重新登录。`, providerUnavailable: (name: string) => `${name} 已登录，但当前 provider 状态不可用。`,
  },
} as const;
const zhTwCopy = {
  detail: {
    deviceCode: '登入碼：',
    delete: '刪除', cancel: '取消', deleteUnused: '不再需要，刪除連線',
    deleteFailed: '刪除模型連線失敗', credentialReadFailed: '讀取模型憑據狀態失敗', refreshFailed: '重新整理模型連線失敗',
    saveFailed: '儲存模型連線失敗', saveModelsFailed: '儲存啟用模型失敗',
    modelKey: '模型金鑰', pasteModelKey: '貼上模型金鑰', getModelKey: '取得模型金鑰', saving: '儲存中…',
    advancedRequest: '高階請求設定', advancedRequestHelp: '為這個連線的 HTTP 請求新增請求頭和額外 JSON 請求體。請求頭值作為憑據儲存在本機。',
    requestHeaders: '自訂請求頭', headerName: '請求頭名稱', headerValue: '請求頭值', retainedHeaderValue: '保留已儲存的值', addHeader: '新增請求頭', removeHeader: '移除', noRequestHeaders: '未設定自訂請求頭。',
    extraRequestBody: '額外請求體（JSON）', extraRequestBodyHelp: '僅新增頂層欄位；若與 Maka 生成的欄位重名，請求會明確失敗。', requestCustomizationInvalid: '請求設定無效', requestHeadersInvalidDetail: '請檢查請求頭名稱和值。', requestBodyInvalidDetail: '請輸入符合要求的 JSON 物件。', saveAdvancedRequest: '儲存高階請求設定', configuredHeaders: (count: number) => `${count} 個請求頭`, noAdvancedRequest: '未設定',
    oauthLoggedIn: 'OAuth 已登入', oauthLoading: 'OAuth 狀態讀取中', oauthUnknown: 'OAuth 狀態未知', oauthWaiting: '等待 OAuth 登入',
    oauthLoggedInDetail: '該模型連線使用主程序儲存的 OAuth access token；若請求提示需要重新登入，請到帳號連線重新授權。',
    oauthLoadingDetail: '正在讀取本機 OAuth 登入狀態，讀取完成前不會把未知狀態顯示成未登入。',
    oauthUnknownDetail: '暫時無法讀取本機 OAuth 登入狀態；請重新整理頁面或重新開啟設定。',
    oauthWaitingDetail: '請到帳號連線完成登入；登入成功後會自動出現在模型連線裡。',
    providerRetired: '此模型服務已停用',
    providerRetiredDetail:
      '這條連線已無法用於對話。請新增其他模型連線，並選擇新的預設模型；原有對話記錄會保留。',
    credentialLoadingDetail: '正在讀取模型憑據狀態，讀取完成前暫不測試連線或重新整理模型。',
    credentialUnknownDetail: '模型憑據狀態暫時沒重新整理成功，已避免把未知狀態顯示成未登入或未設定。',
    testConnection: '測試連線',
    updateModels: '更新模型目錄', endpoint: '服務地址',
    connectionName: '名稱',
    connectionNamePlaceholder: '給這個連線起個名字',
    addModel: '新增模型',
    addModelConfirm: '新增',
    addModelIdField: '模型 ID',
    addModelIdFieldHelp: '需與服務商完全一致，區分大小寫。',
    addModelIdPlaceholder: 'deepseek-v4-flash-0731',
    addModelIdRequired: '請填寫模型 ID。',
    addModelIdDuplicate: '該模型已在列表中。',
    addModelContextWindow: '上下文視窗',
    addModelContextWindowHelp: '服務商模型頁給出的最大 token 數。缺少它 Maka 只能按 32k 處理，長對話會被提前截斷。',
    addModelContextWindowRequired: '請填寫上下文視窗。',
    contextWindowInputInvalid: '請輸入正整數 token 數或 K/M 縮寫，例如 128000、128K、1.5M。',
    credentials: '連線', dangerZone: '刪除連線', deleteRowHelp: '此操作不可撤銷。',
    credentialsHelp: '金鑰只儲存在本機。',
    credentialsHelpAccount: '登入權杖只儲存在本機。',
    modelManagementHelp: '這些模型會出現在任務的模型選擇器裡。',
    ...zhTwCapabilitiesCopy,
    capabilitiesHelp: '僅套用至此連線中的這個模型，儲存後生效。',
    // Row affordances (settings-sidebar 的 InfoRow / ExpandableRow 語言)：一行
    // 只報狀態，改的時候才展開成輸入框。
    change: '更換', set: '設定', edit: '編輯', save: '儲存',
    endpointManaged: '由帳號登入或服務商管理',
    endpointMissing: '尚未設定服務地址',
    endpointModelOverridesNote: '部分模型會透過其他服務端點發送請求',
    endpointCredentialsMasked: '已儲存的地址內嵌憑據,編輯時預設隱藏',
    modelManagement: '模型',
    disconnectAndDelete: '退出帳號並刪除',
    login: '登入', loggingIn: '登入中…', relogin: '重新登入',
    oauthReloginDetail: '若請求提示需要重新登入，點這裡重新走一遍授權。',
    oauthStartDetail: '點下方按鈕開啟瀏覽器完成登入，授權成功後會自動重新整理這裡的狀態。',
    status: '連線狀態', statusHealthy: '正常', statusUntested: '未測試',
    modelsSummary: (enabled: number, total: number) => `已啟用 ${enabled} / ${total}`,
    filterModels: '搜尋模型', noModelsMatch: '找不到符合的模型',
    enableModelAria: (name: string) => `啟用模型 ${name}`,
    declareCapabilities: '設定參數', declareCapabilitiesAria: (name: string) => `設定模型參數：${name}`,
    modelUndescribed: '待設定參數',
    noModels: '暫無可選模型，請先更新模型目錄。',
    keySet: '已設定', statusLoading: '正在讀取狀態', credentialUnknown: '憑據狀態未知', keyMissing: '尚未設定金鑰',
    keyTroubleshooting: '模型金鑰 / 服務地址 / 代理設定', endpointTroubleshooting: '本地服務 / 服務地址 / 代理設定', oauthTroubleshooting: 'OAuth 登入 / 代理設定',
    unknownDescription: (provider: string) => `該連線使用的 provider「${provider}」在目前版本未註冊。設定和憑據會保留，切回支援它的版本即可繼續使用。`,
    deleteProviderTitle: (name: string) => `刪除供應商 ${name}？`,
    deleteConnectionTitle: (name: string) => `刪除模型連線 ${name}？`,
    deleteUnknownDescription: '刪除後，支援該 provider 的其他版本也無法恢復這條連線及其憑據。',
    deleteDescription: (isDefault: boolean, disconnectsAccount: boolean) => [
      disconnectsAccount
        ? '這會退出本機帳號、刪除 OAuth 憑據和模型連線；重新整理後不會自動重建立立。'
        : '這會刪除模型連線及其本機憑據；如需再次使用，需要重新新增。',
      isDefault
        ? '它目前是預設連線；刪除後預設模型會變成未設定，已有任務可能需要重新選擇模型。'
        : '',
    ].filter(Boolean).join(' '),
    connectionSuccess: (name: string) => `連線成功 · ${name}`, connectionFailed: (name: string) => `連線失敗 · ${name}`,
    connectionFallbackTitle: (name: string) => `連線可用 · ${name}`,
    connectionFallbackDetail: (selected: readonly string[], tested: string) =>
      `你選擇的 ${selected.join('、')} 目前沒有回應，已改用 ${tested} 驗證連線可用；任務中繼續使用你選擇的模型可能會失敗。`,
    connectionTestError: (name: string) => `連線測試出錯 · ${name}`, modelsFetched: (count: number, name: string) => `已拉取 ${count} 個模型 · ${name}`,
    modelsFetchFailed: (name: string) => `拉取模型失敗 · ${name}`,
    modelsFetchFailedDetail: (message: string, troubleshooting: string) => `${message} · 目前繼續顯示靜態列表，請確認 ${troubleshooting} 後重試。`,
    authTroubleshooting: (value: string) => `鑑權失敗，請確認 ${value} 後重試。`, recheckTroubleshooting: (value: string) => `檢查 ${value} 後重試。`,
    modelKeyAria: (name: string) => `${name} 模型金鑰`,
    usage: {
      title: '帳戶用量',
      refresh: '重新整理',
      refreshing: '重新整理中…',
      current: '目前使用',
      unavailable: '暫時取不到用量資料。',
      unsupported: '此連線不支援檢視用量。',
      unauthorized: '用量讀取被拒絕：金鑰可能已失效或權限不足，請更新模型金鑰後重試。',
      partiallyUnauthorized: '部分用量資料被拒絕：金鑰缺少相應權限，以下為可讀取的部分。請更新模型金鑰後重試。',
      windowLabels: { fiveHour: '5 小時視窗', weekly: '每週視窗', monthly: '月額度' },
      requests: '請求',
      failed: (count: number) => `失敗 ${count}`,
      successRate: '成功率',
      cost: '花費',
      tokens: 'Token',
      tokensBreakdown: (input: string, output: string) => `${input} 入 / ${output} 出`,
      resetsAt: (when: string) => `重設於 ${when}`,
      periodEnd: (when: string) => `帳期截止 ${when}`,
      updatedAt: (when: string) => `更新於 ${when}`,
      unlimited: '不限',
    },
  },
  shared: {
    connectionStale: '連線狀態已更新，請重新整理清單後再刪除。',
    actionFallback: '模型連線服務暫時不可用，請稍後重試。', rateLimit: '目前帳號或模型服務觸發速率限制，請稍後重試。',
    timeout: '請求超時，請檢查網路或代理後重試。', unavailable: '模型服務暫時不可用，請稍後重試。',
    network: '網路錯誤，請檢查服務地址或代理設定後重試。', statusUnavailable: '連線測試狀態暫時無法顯示，請重新測試。',
    filterMatches: (count: number) => (count === 0 ? '沒有符合的結果' : `${count} 個符合結果`),
    connectionStatuses: { retired: '已停用 · 請刪除', reauth: '需要重新登入', disabledFailed: '暫不可用 · 上次連線失敗', disabled: '暫不可用', failed: '上次連線失敗' },
    lastTest: {
      auth: '鑑權失敗', timeout: '請求超時', provider_unavailable: '模型服務回傳錯誤', network: '網路錯誤', invalid_response: '模型服務回傳錯誤', unknown: '連線測試失敗',
    },
  },
  panel: {
    groups: { recommended: '推薦', plans: '訂閱計劃', api: 'API', aggregators: '聚合服務', local: '本地' },
    loadFailed: '載入模型連線失敗', loadingAria: '正在載入模型供應商', connections: '模型連線',
    connectionsHelp: '已啟用的模型會顯示在任務的模型選擇器中。',
    retry: '點選重試。', empty: '還沒有模型連線', connectionRemoved: '原連線已刪除或移除，已返回模型連線列表。',
    connectedLoading: '帳號已連線，正在載入新的模型連線…', connectedLoadFailed: '帳號已連線，但暫時無法載入新的模型連線。',
    connectionIdentityChanged: '新連線的身分與登入結果不一致，請返回連線列表後重試。',
    emptyHelp: '從下方的常用服務商開始，或瀏覽全部服務商。', recommended: '推薦服務商', browseAll: '查看全部服務商',
    default: '預設', setDefault: '設為預設', setDefaultTitle: '讓新任務預設使用這個連線', setDefaultPending: '設定中…', setDefaultFailed: '設為預設失敗', addHelp: '選擇帳號登入、模型計劃、API、聚合服務或本地執行時。',
    searchPlaceholder: '搜尋服務商', searchAria: '搜尋模型服務商', noMatch: '沒有符合的服務商', clearSearch: '清除搜尋',
    createSubtitle: '完成必要設定後，連線會出現在模型頁上方。', connection: '模型連線',
    count: (value: number) => `· ${value}`, modelCount: (value: number) => `${value} 個模型`, connectTitle: (name: string) => `連線 ${name}`,
    chipAria: (name: string, provider: string, isDefault: boolean, status?: string) => `模型連線：${name}，供應商：${provider}${isDefault ? '，預設連線' : ''}${status ? `，${status}` : ''}`,
    addConnection: '新增連線', backToList: '返回模型連線', backToCatalog: '返回服務商列表',
  },
  catalog: {
    unavailable: '未開放',
    cardAria: (name: string, description: string) => `新增模型供應商：${name}，${description}`,
  },
  add: {
    slugIssues: { required: '請填寫連線標識', format: '連線標識只能包含小寫字母、數字和連字號', too_long: '連線標識不能超過 64 個字元' }, duplicateSlug: '連線標識已存在', cloudflareAccount: '請填寫 Cloudflare Account ID', endpointRequired: '這個供應商需要填寫服務地址',
    accountLogin: '請到帳號連線完成登入；登入成功後會自動建立模型連線。',
    apiKeyPlaceholder: '輸入或貼上 API Key', cancel: '取消', accountTitle: '使用帳號連線登入',
    advancedRequest: '高階請求設定', expandAdvancedRequest: '展開高階請求設定', collapseAdvancedRequest: '收起高階請求設定',
    requestHeaders: '自訂請求頭', headerName: '請求頭名稱', headerValue: '請求頭值', retainedHeaderValue: '保留已儲存的值', addHeader: '新增請求頭', removeHeader: '移除', noRequestHeaders: '未設定自訂請求頭。',
    extraRequestBody: '額外請求體（JSON）', extraRequestBodyHelp: '僅新增頂層欄位；與 Maka 生成欄位重名時會明確失敗。請求頭值將作為憑據儲存在本機。', requestCustomizationInvalid: '請檢查高階請求設定。',
    accountDetail: '不要在這裡手動新增；請回到模型連線頁的帳號連線完成登入，Maka 會自動建立並重新整理模型連線。',
    slug: '連線標識', name: '顯示名稱',
    accountIdPlaceholder: '填寫帳號 ID',
    saving: '儲存中…', save: '儲存供應商', keyRequired: (name: string) => `請填寫 ${name} API Key`,
    apiKeyLabel: 'API Key', accountIdLabel: 'Cloudflare Account ID', endpointLabel: '服務地址',
    defaultModel: '預設模型', defaultModelPlaceholder: '留空即可，儲存後自動拉取', defaultModelHelp: '儲存後 Maka 會向該端點拉取模型目錄。只有當端點不提供目錄時，才需要在這裡手填一個模型 ID。',
    stepsAria: '新增連線步驟', stepCredentials: '金鑰', stepModels: '選擇模型',
    onboardingVerifyAndChoose: '驗證並選擇模型', onboardingVerifying: '正在驗證金鑰並取得模型…',
    onboardingChooseModels: '選擇此連線使用的模型', onboardingChooseModelsHelp: '新增後仍可在連線詳細資料中啟用其他模型。', onboardingEnabledModels: '啟用的模型', onboardingSearchModels: '搜尋模型', onboardingAddConnection: '新增連線', onboardingBack: '返回修改',
    onboardingSelectedCount: (selected: number, total: number) => `已選 ${selected} / ${total}`, onboardingSelectAll: '全選', onboardingClearAll: '取消全選', onboardingNoModelsMatch: '找不到符合的模型',
    onboardingDefaultModel: '預設模型', onboardingDefaultModelHelp: '新任務將預設使用此模型，僅可在已勾選的模型中選擇。',
    onboardingAuthFailed: '金鑰驗證失敗，請檢查後重試。', onboardingTimeout: '驗證逾時，請檢查網路或 Proxy 後重試。', onboardingNetwork: '無法連線至模型服務，請檢查網路、Proxy 或服務位址。', onboardingUnavailable: '模型連線服務暫時無法使用，請稍後重試。', onboardingInvalidResponse: '模型服務回傳無法辨識的結果，請稍後重試。', onboardingCatalogFull: '連線數量已達上限，請先刪除不再使用的連線。', onboardingModelsChanged: '可用模型已變更，請重新驗證後選擇。', onboardingNoModels: '未發現可用模型，目前未建立連線。', onboardingSelectModel: '請至少啟用一個模型。',
    onboardingOutcomeUnknown: '暫時無法確認儲存結果', onboardingOutcomeUnknownDetail: '請勿再次新增，以免建立重複連線。重新載入連線列表並檢查該連線是否已出現；仍不確定時請先重新連線 Runtime Host。', onboardingReloadConnections: '重新載入連線列表', onboardingRestart: '仍要新增另一個連線',
    ...zhTwCapabilitiesCopy,
  },
  oauthFlow: {
    refreshFailed: '重新整理登入狀態失敗', accountActionFailed: (name: string) => `${name} 帳號操作失敗`, loginFailedRetry: '登入失敗，請稍後重試。',
    retry: '請稍後再試。', startFailed: '無法開始登入', startFailedRetry: '無法開始登入，請稍後再試。', openFailed: '無法開啟瀏覽器',
    openFailedRetry: '無法開啟瀏覽器，請稍後重試。', loginSuccess: '登入成功', bound: (name: string) => `${name} 已繫結本機。`,
    incomplete: '登入未完成', incompleteRetry: '登入未完成，請重新開啟瀏覽器授權。', loginFailed: '登入失敗',
    logoutDescription: '將刪除本機儲存的訂閱憑據，之後需要重新登入才能繼續使用這些 OAuth 模型。', logout: '退出登入', cancel: '取消',
    loggedOut: '已退出登入', credentialsCleared: '本地憑據已清除。', logoutFailed: '退出失敗', logoutFailedRetry: '退出登入失敗，請稍後重試。',
    serviceUnavailable: '登入服務暫時不可用，請檢查網路後重試。',
    resultCodes: {
      copilot_classic_pat_unsupported: 'GitHub Copilot 不支援 classic PAT；請使用相容 OAuth 登入或具有 Copilot Requests 權限的 fine-grained PAT。',
      copilot_credential_type_unsupported: '目前的 GitHub 憑據類型不受支援；請使用相容 OAuth 登入或 fine-grained PAT。',
      copilot_local_credential_missing: '找不到可匯入的 GitHub 憑據；請先使用 gh 登入或設定相容憑據。',
      copilot_import_no_credential: 'GitHub Copilot 登入沒有產生可用憑據。',
      copilot_import_superseded: 'GitHub Copilot 帳號在匯入期間發生變化，請重試。',
      copilot_subscription_unavailable: '目前的 GitHub 帳號沒有可用的 Copilot 訂閱權限。',
      copilot_credential_import_rejected: '目前的 GitHub 憑據無法匯入，請檢查憑據後重試。',
      copilot_subscription_check_failed: '暫時無法驗證 GitHub Copilot 訂閱狀態，請稍後重試。',
      copilot_import_commit_failed: 'GitHub Copilot 登入未能寫入 Runtime Host。',
      experimental_disabled: '本機未啟用該帳號登入方式；可改用匯入相容憑據，或由管理員啟用後重試。',
      login_in_progress: '上一輪登入仍在進行，等它結束後再按登入。',
      presentation_failed: '無法開啟系統瀏覽器完成登入，請檢查是否封鎖了彈出式視窗後再試。',
    },
    logoutTitle: (name: string) => `退出 ${name} 登入？`,
  },
  oauthSection: {
    signedIn: '已登入', codexDescription: 'ChatGPT Plus / Pro 訂閱帳號登入。', xaiDescription: 'SuperGrok / X Premium 帳號登入。',
    configuredConnections: (count: number) => `已有 ${count} 個連線 · 新增另一個帳號`,
    copilotDescription: '匯入相容 GitHub 憑據連線 Copilot 訂閱。', serviceUnavailable: '登入服務暫時不可用，請檢查網路後重試。',
    aria: 'OAuth 登入',
    staleState: 'OAuth 登入狀態暫時沒重新整理成功，已保留上一次狀態。',
    codexDetail: '點選下方按鈕開啟裝置授權頁，並在頁面中輸入這裡顯示的登入碼。', xaiDetail: '點選下方按鈕開啟瀏覽器登入，授權完成後會自動回寫。', deviceCode: '登入碼：',
    openingBrowser: '開啟瀏覽器…', waitingAuthorization: '等待瀏覽器授權…', logout: '退出登入', loggingOut: '退出中…',
    copilotSubtitle: '匯入相容的 GitHub 登入；token 不會暴露給渲染程序。', copilotImported: '已匯入 GitHub Copilot 訂閱帳號。',
    copilotSetup: '請設定具有 Copilot Requests 權限的 fine-grained PAT；普通 gh auth login 可能不包含該權限。', importing: '匯入中…',
    copilotSignIn: '使用 GitHub 登入', copilotActionFailed: 'GitHub Copilot 帳號操作失敗',
    copilotSignInDisabledHint: '本機未啟用 GitHub 登入；請改用匯入相容憑據，或由管理員啟用後重試。',
    importCredential: '匯入相容憑據',
    loadingAccount: '正在載入帳號狀態…', authorizing: '請在彈出的瀏覽器視窗完成登入。', refreshing: '正在重新整理存取權杖…', refreshTokenFailed: '權杖重新整理失敗，請重新登入。',
    cardAria: (intent: 'add' | 'import' | 'manage', name: string, status: string | undefined, description: string) => `${intent === 'add' ? '新增' : intent === 'import' ? '匯入' : '管理'}帳號連線：${name}${status ? `，狀態：${status}` : ''}，${description.replace(/[。.!！？?]+$/u, '')}`,
    connectTitle: (name: string) => `連線 ${name}`, addAccountTitle: (name: string) => `新增 ${name} 帳號`, login: (name: string) => `登入 ${name}`, loginAndAdd: '登入並新增', signedOut: (name: string) => `${name} 尚未登入。`,
    storageFailed: (name: string) => `${name} 本地憑據讀取失敗，請重新登入。`, providerUnavailable: (name: string) => `${name} 已登入，但目前 provider 狀態不可用。`,
  },
} as const;

export type ProviderSettingsCopy = WidenCopy<typeof zhCopy>;

const enCopy: ProviderSettingsCopy = {
  detail: {
    delete: 'Delete', cancel: 'Cancel', deleteUnused: 'Delete unused connection',
    deleteFailed: 'Failed to delete model connection', credentialReadFailed: 'Failed to read model credential status', refreshFailed: 'Failed to refresh model connection',
    saveFailed: 'Failed to save model connection', saveModelsFailed: 'Failed to save enabled models',
    modelKey: 'Model key', pasteModelKey: 'Paste model key', getModelKey: 'Get model key', saving: 'Saving…',
    advancedRequest: 'Advanced request settings', advancedRequestHelp: 'Add HTTP headers and extra JSON request-body fields for this connection. Header values stay in the local credential vault.',
    requestHeaders: 'Custom request headers', headerName: 'Header name', headerValue: 'Header value', retainedHeaderValue: 'Keep saved value', addHeader: 'Add header', removeHeader: 'Remove', noRequestHeaders: 'No custom request headers.',
    extraRequestBody: 'Extra request body (JSON)', extraRequestBodyHelp: 'Adds top-level fields only. A collision with a Maka-generated field fails explicitly.', requestCustomizationInvalid: 'Invalid request settings', requestHeadersInvalidDetail: 'Check the request header names and values.', requestBodyInvalidDetail: 'Enter a valid JSON object that meets the requirements.', saveAdvancedRequest: 'Save advanced request settings', configuredHeaders: (count: number) => `${count} ${count === 1 ? 'header' : 'headers'}`, noAdvancedRequest: 'Not configured',
    oauthLoggedIn: 'OAuth signed in', oauthLoading: 'Reading OAuth status', oauthUnknown: 'OAuth status unavailable', oauthWaiting: 'Waiting for OAuth sign-in',
    oauthLoggedInDetail: 'This model connection uses an OAuth access token stored by the main process. If a request asks you to sign in again, reauthorize it under account connections.',
    oauthLoadingDetail: 'Reading the local OAuth status. An unknown state will not be shown as signed out.',
    oauthUnknownDetail: 'The local OAuth status is temporarily unavailable. Refresh the page or reopen Settings.',
    oauthWaitingDetail: 'Complete sign-in under account connections. The model connection appears automatically afterward.',
    providerRetired: 'This provider is retired',
    providerRetiredDetail:
      'This connection can no longer be used for conversations. Add another provider and choose a new default model. Existing conversations are kept.',
    credentialLoadingDetail: 'Reading model credential status. Connection tests and model refresh are paused until it finishes.',
    credentialUnknownDetail: 'Model credential status could not be refreshed, so the connection is not being mislabeled as signed out or unconfigured.',
    testConnection: 'Test connection',
    updateModels: 'Update model catalog', endpoint: 'Service URL',
    connectionName: 'Name',
    connectionNamePlaceholder: 'Name this connection',
    addModel: 'Add model',
    addModelConfirm: 'Add',
    addModelIdField: 'Model ID',
    addModelIdFieldHelp: 'Must match the provider exactly, including case.',
    addModelIdPlaceholder: 'deepseek-v4-flash-0731',
    addModelIdRequired: 'Enter a model ID.',
    addModelIdDuplicate: 'This model is already in the list.',
    addModelContextWindow: 'Context window',
    addModelContextWindowHelp:
      "The maximum token count from the provider's model page. Without it Maka can only assume 32k, and long conversations get truncated early.",
    addModelContextWindowRequired: 'Enter a context window.',
    contextWindowInputInvalid: 'Enter a positive whole token count or K/M value, such as 128000, 128K, or 1.5M.',
    credentials: 'Connection', dangerZone: 'Delete connection', deleteRowHelp: 'This cannot be undone.',
    credentialsHelp: 'The key stays on this machine.',
    credentialsHelpAccount: 'The sign-in token stays on this machine.',
    modelManagementHelp: 'These models appear in the chat model picker.',
    ...enCapabilitiesCopy,
    capabilitiesHelp: 'Applies to this model on this connection. Changes take effect on save.',
    change: 'Change', set: 'Set', edit: 'Edit', save: 'Save',
    endpointManaged: 'Managed by account sign-in or the provider',
    endpointMissing: 'No service URL configured',
    endpointModelOverridesNote: 'Some models send requests through a different endpoint',
    endpointCredentialsMasked: 'The saved URL embeds credentials and stays masked while editing',
    modelManagement: 'Models',
    disconnectAndDelete: 'Sign out and delete',
    login: 'Sign in', loggingIn: 'Signing in…', relogin: 'Sign in again',
    oauthReloginDetail: 'If a request asks you to sign in again, restart authorization here.', deviceCode: 'Sign-in code:',
    oauthStartDetail: 'Open the browser below to sign in. This status refreshes automatically after authorization.',
    status: 'Connection status', statusHealthy: 'Healthy', statusUntested: 'Not tested',
    modelsSummary: (enabled: number, total: number) => `${enabled} of ${total} enabled`,
    filterModels: 'Search models', noModelsMatch: 'No matching models',
    enableModelAria: (name: string) => `Enable model ${name}`,
    declareCapabilities: 'Set parameters', declareCapabilitiesAria: (name: string) => `Set model parameters: ${name}`,
    modelUndescribed: 'Parameters not configured',
    noModels: 'No models are available. Update the model catalog first.',
    keySet: 'Set', statusLoading: 'Reading status', credentialUnknown: 'Credential status unavailable', keyMissing: 'No key set',
    keyTroubleshooting: 'model key, service URL, and proxy settings', endpointTroubleshooting: 'local service, service URL, and proxy settings', oauthTroubleshooting: 'OAuth sign-in and proxy settings',
    unknownDescription: (provider: string) => `The provider “${provider}” used by this connection is not registered in the current version. Its configuration and credentials are preserved for a supported version.`,
    deleteProviderTitle: (name: string) => `Delete provider ${name}?`,
    deleteConnectionTitle: (name: string) => `Delete model connection ${name}?`,
    deleteUnknownDescription: 'After deletion, another version that supports this provider cannot restore the connection or its credentials.',
    deleteDescription: (isDefault: boolean, disconnectsAccount: boolean) => [
      disconnectsAccount
        ? 'This signs out the local account and deletes its OAuth credential and model connection. It will not be recreated on refresh.'
        : 'This deletes the model connection and its local credential. Add it again to use it later.',
      isDefault
        ? 'It is currently the default connection; the default model becomes unset and existing chats may need another model selected.'
        : '',
    ].filter(Boolean).join(' '),
    connectionSuccess: (name: string) => `Connected · ${name}`, connectionFailed: (name: string) => `Connection failed · ${name}`,
    connectionFallbackTitle: (name: string) => `Connection works · ${name}`,
    connectionFallbackDetail: (selected: readonly string[], tested: string) =>
      `Your selected ${selected.join(', ')} didn't respond; verified the connection with ${tested} instead. Tasks using your selected model may fail.`,
    connectionTestError: (name: string) => `Connection test error · ${name}`, modelsFetched: (count: number, name: string) => `Fetched ${count} ${count === 1 ? 'model' : 'models'} · ${name}`,
    modelsFetchFailed: (name: string) => `Failed to fetch models · ${name}`,
    modelsFetchFailedDetail: (message: string, troubleshooting: string) => `${message} · The static list remains visible. Check ${troubleshooting} and try again.`,
    authTroubleshooting: (value: string) => `Authentication failed. Check ${value} and try again.`, recheckTroubleshooting: (value: string) => `Check ${value} and try again.`,
    modelKeyAria: (name: string) => `${name} model key`,
    usage: {
      title: 'Account usage',
      refresh: 'Refresh',
      refreshing: 'Refreshing…',
      current: 'In use',
      unavailable: 'No usage data is available right now.',
      unsupported: 'This connection does not report usage.',
      unauthorized: 'Usage was refused — the key may be expired or lack the scope. Update the model key and try again.',
      partiallyUnauthorized: 'Some usage was refused — the key lacks the scope for it. Below is what could be read; update the model key and try again.',
      windowLabels: { fiveHour: '5-hour window', weekly: 'Weekly window', monthly: 'Monthly credits' },
      requests: 'Requests',
      failed: (count: number) => `${count} failed`,
      successRate: 'Success rate',
      cost: 'Cost',
      tokens: 'Tokens',
      tokensBreakdown: (input: string, output: string) => `${input} in / ${output} out`,
      resetsAt: (when: string) => `Resets ${when}`,
      periodEnd: (when: string) => `Period ends ${when}`,
      updatedAt: (when: string) => `Updated ${when}`,
      unlimited: 'Unlimited',
    },
  },
  shared: {
    connectionStale: 'The connection changed while deleting. Refresh the list and try again.',
    actionFallback: 'The model connection service is temporarily unavailable. Try again later.', rateLimit: 'This account or model service is rate-limited. Try again later.',
    timeout: 'The request timed out. Check the network or proxy and try again.', unavailable: 'The model service is temporarily unavailable. Try again later.',
    network: 'Network error. Check the service URL or proxy settings and try again.', statusUnavailable: 'The connection test status is temporarily unavailable. Test again.',
    filterMatches: (count: number) => (count === 0 ? 'No matches' : count === 1 ? '1 match' : `${count} matches`),
    connectionStatuses: { retired: 'Retired · delete it', reauth: 'Sign-in required', disabledFailed: 'Unavailable · last connection failed', disabled: 'Unavailable', failed: 'Last connection failed' },
    lastTest: {
      auth: 'Authentication failed', timeout: 'Request timed out', provider_unavailable: 'Model service returned an error', network: 'Network error', invalid_response: 'Model service returned an error', unknown: 'Connection test failed',
    },
  },
  panel: {
    groups: { recommended: 'Recommended', plans: 'Subscription plans', api: 'API', aggregators: 'Aggregators', local: 'Local' },
    loadFailed: 'Failed to load model connections', loadingAria: 'Loading model providers', connections: 'Connections',
    connectionsHelp: 'These connections and their enabled models appear in the chat model picker.',
    retry: 'Select to retry.', empty: 'No model connections yet', connectionRemoved: 'The original connection was deleted or removed. Returned to the connection list.',
    connectedLoading: 'Connection added. Loading its details…', connectedLoadFailed: 'Connection added, but the connection list could not be refreshed yet.',
    connectionIdentityChanged: 'The new connection identity did not match the sign-in result. Return to the connection list and try again.',
    emptyHelp: 'Start with a common provider below, or browse them all.', recommended: 'Recommended providers', browseAll: 'Browse all providers',
    default: 'Default', setDefault: 'Set as default', setDefaultTitle: 'New chats will use this connection', setDefaultPending: 'Setting…', setDefaultFailed: 'Could not set as default', addHelp: 'Choose account sign-in, a model plan, API, aggregator, or local runtime.',
    searchPlaceholder: 'Search providers', searchAria: 'Search model providers', noMatch: 'No matching providers', clearSearch: 'Clear search',
    createSubtitle: 'After required setup, the connection appears above on the Models page.', connection: 'Model connection',
    count: (value: number) => `· ${value}`, modelCount: (value: number) => `${value} ${value === 1 ? 'model' : 'models'}`, connectTitle: (name: string) => `Connect ${name}`,
    chipAria: (name: string, provider: string, isDefault: boolean, status?: string) => `Model connection: ${name}; provider: ${provider}${isDefault ? '; default connection' : ''}${status ? `; ${status}` : ''}`,
    addConnection: 'Add connection', backToList: 'Back to model connections', backToCatalog: 'Back to the provider list',
  },
  catalog: {
    unavailable: 'Unavailable',
    cardAria: (name: string, description: string) => `Add model provider: ${name}; ${description}`,
  },
  add: {
    slugIssues: { required: 'Enter a connection identifier', format: 'Connection identifiers use lowercase letters, digits, and hyphens', too_long: 'Connection identifiers are at most 64 characters' }, duplicateSlug: 'Connection identifier already exists', cloudflareAccount: 'Enter the Cloudflare Account ID', endpointRequired: 'This provider requires a service URL',
    accountLogin: 'Complete sign-in under account connections. A model connection is created automatically afterward.',
    apiKeyPlaceholder: 'Enter or paste API key', cancel: 'Cancel', accountTitle: 'Sign in with an account connection',
    advancedRequest: 'Advanced request settings', expandAdvancedRequest: 'Show advanced request settings', collapseAdvancedRequest: 'Hide advanced request settings',
    requestHeaders: 'Custom request headers', headerName: 'Header name', headerValue: 'Header value', retainedHeaderValue: 'Keep saved value', addHeader: 'Add header', removeHeader: 'Remove', noRequestHeaders: 'No custom request headers.',
    extraRequestBody: 'Extra request body (JSON)', extraRequestBodyHelp: 'Adds top-level fields only. A collision with a Maka-generated field fails explicitly. Header values stay in the local credential vault.', requestCustomizationInvalid: 'Check the advanced request settings.',
    accountDetail: 'Do not add this provider manually here. Return to account connections and sign in; Maka creates and refreshes the model connection automatically.',
    slug: 'Connection identifier', name: 'Display name',
    accountIdPlaceholder: 'Enter account ID',
    saving: 'Saving…', save: 'Save provider', keyRequired: (name: string) => `Enter the ${name} API key`,
    apiKeyLabel: 'API key', accountIdLabel: 'Cloudflare Account ID', endpointLabel: 'Service URL',
    defaultModel: 'Default model', defaultModelPlaceholder: 'Leave empty — fetched after saving', defaultModelHelp: 'Maka fetches the model catalog from this endpoint after saving. Type a model id here only if the endpoint serves no catalog.',
    stepsAria: 'Steps to add the connection', stepCredentials: 'Key', stepModels: 'Choose models',
    onboardingVerifyAndChoose: 'Verify and choose models', onboardingVerifying: 'Verifying the key and loading models…',
    onboardingChooseModels: 'Choose models for this connection', onboardingChooseModelsHelp: 'You can enable more models from the connection details later.', onboardingEnabledModels: 'Enabled models', onboardingSearchModels: 'Search models', onboardingAddConnection: 'Add connection', onboardingBack: 'Back to edit',
    onboardingSelectedCount: (selected: number, total: number) => `${selected} of ${total} selected`, onboardingSelectAll: 'Select all', onboardingClearAll: 'Deselect all', onboardingNoModelsMatch: 'No matching models',
    onboardingDefaultModel: 'Default model', onboardingDefaultModelHelp: 'New chats start on this model. Only selected models can be chosen.',
    onboardingAuthFailed: 'The key could not be verified. Check it and try again.', onboardingTimeout: 'Verification timed out. Check the network or proxy and try again.', onboardingNetwork: 'Could not reach the model provider. Check the network, proxy, or service URL.', onboardingUnavailable: 'The model connection service is unavailable. Try again later.', onboardingInvalidResponse: 'The model provider returned an unrecognized response. Try again later.', onboardingCatalogFull: 'The connection limit has been reached. Remove an unused connection first.', onboardingModelsChanged: 'The available models changed. Verify again and make a new selection.', onboardingNoModels: 'No usable models were found. No connection was created.', onboardingSelectModel: 'Enable at least one model.',
    onboardingOutcomeUnknown: 'The save result cannot be confirmed', onboardingOutcomeUnknownDetail: 'Do not add it again yet, because that could create a duplicate connection. Reload the connection list and check whether this connection appeared; reconnect the Runtime Host if the result is still unclear.', onboardingReloadConnections: 'Reload connection list', onboardingRestart: 'Add another connection anyway',
    ...enCapabilitiesCopy,
  },
  oauthFlow: {
    refreshFailed: 'Failed to refresh sign-in status', accountActionFailed: (name: string) => `${name} account action failed`, loginFailedRetry: 'Sign-in failed. Try again later.',
    retry: 'Try again later.', startFailed: 'Could not start sign-in', startFailedRetry: 'Could not start sign-in. Try again later.', openFailed: 'Could not open browser',
    openFailedRetry: 'Could not open the browser. Try again.', loginSuccess: 'Signed in', bound: (name: string) => `${name} is connected to this device.`,
    incomplete: 'Sign-in incomplete', incompleteRetry: 'Sign-in did not finish. Reopen the browser authorization and try again.', loginFailed: 'Sign-in failed',
    logoutDescription: 'This removes the locally stored subscription credentials. You must sign in again to use these OAuth models.', logout: 'Sign out', cancel: 'Cancel',
    loggedOut: 'Signed out', credentialsCleared: 'Local credentials cleared.', logoutFailed: 'Sign-out failed', logoutFailedRetry: 'Sign-out failed. Try again later.',
    serviceUnavailable: 'The sign-in service is temporarily unavailable. Check the network and try again.',
    logoutTitle: (name: string) => `Sign out of ${name}?`,
    resultCodes: {
      copilot_classic_pat_unsupported: 'GitHub Copilot does not accept classic PATs. Use a compatible OAuth login or a fine-grained PAT with the Copilot Requests permission.',
      copilot_credential_type_unsupported: 'This GitHub credential type is not supported. Use a compatible OAuth login or a fine-grained PAT.',
      copilot_local_credential_missing: 'No importable GitHub credential was found. Sign in with gh or configure a compatible credential first.',
      copilot_import_no_credential: 'The GitHub Copilot login produced no usable credential.',
      copilot_import_superseded: 'The GitHub Copilot account changed during import. Try again.',
      copilot_subscription_unavailable: 'This GitHub account has no usable Copilot subscription.',
      copilot_credential_import_rejected: 'This GitHub credential could not be imported. Check it and try again.',
      copilot_subscription_check_failed: 'Could not verify the GitHub Copilot subscription right now. Try again later.',
      copilot_import_commit_failed: 'The GitHub Copilot login could not be committed to Runtime Host.',
      experimental_disabled: 'This sign-in is not enabled on this install. Import a compatible credential instead, or ask an operator to enable it.',
      login_in_progress: 'A previous login is still running. Start again after it settles.',
      presentation_failed: 'Could not open the system browser for login. Check popup blockers and try again.',
    },
  },
  oauthSection: {
    signedIn: 'Signed in', codexDescription: 'Use a ChatGPT Plus / Pro account to add a connection.', xaiDescription: 'Use a SuperGrok or X Premium account to add a connection.',
    configuredConnections: (count: number) => `${count} ${count === 1 ? 'connection' : 'connections'} configured · Add another account`,
    copilotDescription: 'Sign in with GitHub to connect a Copilot subscription, or import compatible credentials.', serviceUnavailable: 'The sign-in service is temporarily unavailable. Check the network and try again.',
    aria: 'OAuth sign-in',
    staleState: 'OAuth sign-in status could not be refreshed. The last known state is preserved. ',
    codexDetail: 'Open the device page below and enter the sign-in code shown here.', xaiDetail: 'Open the browser below to sign in. Authorization is written back automatically.', deviceCode: 'Sign-in code:',
    openingBrowser: 'Opening browser…', waitingAuthorization: 'Waiting for browser authorization…', logout: 'Sign out', loggingOut: 'Signing out…',
    copilotSubtitle: 'Sign in with GitHub, or import compatible credentials. The token is never exposed to the renderer.', copilotImported: 'GitHub Copilot subscription account imported.',
    copilotSetup: 'Sign in with GitHub to connect Copilot, or import an existing gh credential.', importing: 'Importing…',
    copilotSignIn: 'Sign in with GitHub', copilotActionFailed: 'GitHub Copilot account action failed',
    copilotSignInDisabledHint: 'GitHub sign-in is not enabled on this install. Import a compatible credential instead, or ask an operator to enable it.',
    importCredential: 'Import compatible credentials',
    loadingAccount: 'Loading account status…', authorizing: 'Complete sign-in in the browser window.', refreshing: 'Refreshing access token…', refreshTokenFailed: 'Token refresh failed. Sign in again.',
    cardAria: (intent: 'add' | 'import' | 'manage', name: string, status: string | undefined, description: string) => `${intent === 'add' ? 'Add' : intent === 'import' ? 'Import' : 'Manage'} account connection: ${name}${status ? `; status: ${status}` : ''}; ${description.replace(/[。.!！？?]+$/u, '')}`,
    connectTitle: (name: string) => `Connect ${name}`, addAccountTitle: (name: string) => `Add ${name} account`, login: (name: string) => `Sign in to ${name}`, loginAndAdd: 'Sign in and add', signedOut: (name: string) => `${name} is signed out.`,
    storageFailed: (name: string) => `Could not read local credentials for ${name}. Sign in again.`, providerUnavailable: (name: string) => `${name} is signed in, but the provider status is currently unavailable.`,
  },
};

const PROVIDER_SETTINGS_COPY = {
  'zh-CN': zhCopy,
  'zh-TW': zhTwCopy,
  en: enCopy,
} satisfies UiCatalog<ProviderSettingsCopy>;

export function getProviderSettingsCopy(locale: UiLocale): ProviderSettingsCopy {
  return PROVIDER_SETTINGS_COPY[locale];
}

export function subscriptionActionErrorMessage(error: unknown, locale: UiLocale): string {
  const message = error instanceof Error
    ? error.message
    : typeof error === 'string'
      ? error
      : '';
  return subscriptionResultMessage(message, getProviderSettingsCopy(locale).oauthFlow.serviceUnavailable, locale);
}

export type SubscriptionResultInput =
  // `code`/`reason` stay `string` on the wire: a newer host may send a code
  // this client does not know yet, and the guard below maps only known codes.
  | string
  | undefined
  | { readonly code?: string; readonly reason?: string; readonly message?: string };

export function subscriptionResultMessage(input: SubscriptionResultInput, fallback: string, locale: UiLocale): string {
  const { code, reason, message } = typeof input === 'object' && input !== null ? input : { message: input };
  const copy = getProviderSettingsCopy(locale).oauthFlow;
  const mapped = lookupCopy(copy.resultCodes, code) ?? lookupCopy(copy.resultCodes, reason);
  if (mapped) return mapped;
  const raw = redactSecrets(message ?? '').trim();
  if (!raw) return fallback;
  // Prose fallback for Hosts older than the typed reasons; every Desktop-owned
  // producer now sends a code, so nothing local depends on this wording.
  if (/enrollment is disabled for this provider/i.test(raw)) return copy.resultCodes.experimental_disabled;
  if (/already in progress/i.test(raw)) return copy.resultCodes.login_in_progress;
  const classified = generalizedErrorMessageForLocale(new Error(raw), '', locale);
  return classified || fallback;
}
